spring.application.name=agri-backend
server.port=8080

spring.datasource.url=jdbc:h2:file:./backend_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=SA
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.api.base-path=/api
app.weather.api-key=demo_key
app.weather.base-url=http://api.openweathermap.org/data/2.5

logging.level.org.springframework.security=DEBUG
